version: '2'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/vhost.conf:/etc/nginx/conf.d/vhost.conf
      - ./dist:/var/www
    links:
      - php
      - mysql

  php:
    build: ./docker
    volumes:
      - ./dist:/var/www
    links:
      - mysql
      - mail

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./_database/docker:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ">}6pk]j;;H7UTTQnvi7d7T}y3apW2E"
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: "123"

  mail:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

volumes:
  data: {}
